Ehealth/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView

import authentication.views
import forum.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',LoginView.as_view(template_name = 'authentication/login.html') , name='login'),
    path('logout/',authentication.views.logout_user, name='logout'),
    path('signup/',authentication.views.signup_page, name='signup'),
    path('',forum.views.home, name='home'),
     path('forum/',forum.views.forum, name='forum'),
    
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    CREATOR ='CREATOR'
    SUBSCRIBER = 'SUBSCRIBER'
    ROLE_CHOICES = (
        (CREATOR, 'Créateur'),
        (SUBSCRIBER, 'Abonné'),
    )
    profile_photo = models.ImageField()
    role = models.CharField(max_length=30,choices=ROLE_CHOICES)

forum/models.py
from django.conf import settings
from django.db import models


class Blog(models.Model):
    
    title = models.CharField(max_length=128, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    blogs = models.ManyToManyField("self", blank=True,symmetrical=False)
    blog_photo = models.ImageField(null = True , blank = True)


class Message(models.Model):
    content = models.CharField(max_length=5000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_send = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    

authentication/forms.py
# from django import forms
import email
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms




class SignupForm(UserCreationForm,forms.Form):
    first_name = forms.CharField(max_length=63, label = 'Prénom',widget=forms.TextInput(attrs={'required':True}))
    last_name = forms.CharField(max_length=63, label = 'Nom',widget=forms.TextInput(attrs={'required':True}))
    email = forms.EmailField(max_length=63, label = 'Adresse Electronique',widget=forms.TextInput(attrs={'required':True}))
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username','email','first_name', 'last_name','role')
    
        
        



# class LoginForm(forms.Form):

#     username = forms.CharField(max_length=63, label="Nom D'utilisateur")
#     password = forms.CharField(max_length=63, widget = forms.PasswordInput, label='Mot de passe')

forum/forms.py
from django import forms

from . import models



class BlogForm(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = ['title', 'blog_photo']

class MessageForm(forms.ModelForm):
    class Meta:   
        model = models.Message
        fields = ('content',) 

authentication/views.py
from django.views.generic import View
from django.conf import settings
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth import authenticate, login, logout

# Create your views here.


# class LoginPageView(View):
#     template_name = 'authentication/login.html'
#     form_class = forms.LoginForm

#     def get(self,request):
#         form = self.form_class()
#         message =''
#         return render(request,self.template_name, context = {'form' : form, 'message' : message})

#     def post(self,request):
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             user = authenticate(username = form.cleaned_data['username'], password = form.cleaned_data['password'])
#             if user is not None:
#                 login(request,user)
#                 message = f'Bonjour {user.username} vous êtes connecté'
#             else:
#                 message = 'Identifiant invalide'
#         return render(request, self.template_name, context = {'form' : form, 'message' : message})
# def login_page(request):
#     form = forms.LoginForm()
#     message = ''
#     if request.method == 'POST' :
#         form = forms.LoginForm(request.POST)
#         if form.is_valid():
#             user = authenticate(username = form.cleaned_data['username'], password = form.cleaned_data['password'])
#             if user is not None:
#                 login(request,user)
#                 message = f'Bonjour {user.username} vous êtes connecté'
#             else:
#                 message = 'Identifiant invalide'

#     return render(request, 'authentication/login.html', context = {'form' : form, 'message' : message})


def signup_page(request):  
    form = forms.SignupForm()
    if request.method == 'POST' :
        form = forms.SignupForm(request.POST)
        if form.is_valid():
            user = form.save()       
            login(request,user)
            return redirect(settings.LOGIN_REDIRECT_URL)
    return render(request, 'authentication/signup.html', context = {'form' : form})
def logout_user(request):
    logout(request)
    return redirect('login')

forum/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from forum.forms import *
from forum.models import *
# Create your views here.




def home(request):
    return render(request, 'forum/index.html')

# @login_required
# def forum(request):
#     return render(request, 'forum/accueil.html')




# @login_required
# def forum(request):
#     blogs = Blog.objects.all()
     
    
    return render(request,'forum/accueil.html', {'blogs':blogs,})

@login_required
def forum(request):
    blogs = Blog.objects.all()


    form = BlogForm()
    form1 = MessageForm()

    if request.method == 'POST':
        form = BlogForm(request.POST)
        form1 = MessageForm(request.POST)
        if form.is_valid():
            photo = form.save(commit= False)
            photo.author = request.user
            photo.save()
        if form1.is_valid():
            msg = form.save(commit= False)
            msg.author = request.user
            msg.blog = form1.cleaned_data['blog']
            msg.save()

   
            
    return render(request,'forum/accueil.html', {'form':form,'blogs':blogs,'form1':form1})

authentication/templates/authentication/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'authentication/styles.css' %}" />
    <title>Login</title>
</head>
<body>      
    <div class = "center">
        {%  if user.is_authenticated %}
        <p>Vous êtes connecté en tant que {{ request.user }}. <a href="{% url 'logout' %}">Se déconnecter</a></p>
        {% endif %}
        <h1>Login</h1>

        <form method="post" >
             {% for field in form %}
                    <div class="txt_field">
                        {{ field}}
                        <span></span>
                        <label for="{{ field.id_for_label }}">{{field.label}} :</label>
                       
                    </div>
            {% endfor %}

            <!-- <div class="txt_field">
                {{ form.username }}
                <span></span>
                <label for="{{ form.username.id_for_label }}">{{form.username.label}} :</label>
                
            </div>
            <div class="txt_field">
                {{ form.password }}
                <span></span>
                <label for="{{ form.password.id_for_label }}">{{form.password.label}} :</label>
                
            </div> -->
  
           <div class="pass">Forgot Password !</div>
           <input type="submit" value="Login">
            {%  csrf_token %}
            <div class="signup_link">
                    Not a member ! <a href="{% url 'signup' %}">Signup</a>

            </div> 
            
        </form>


    </div>
    

</body>
</html>

authentication/templates/authentication/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'authentication/styles.css' %}" />
    <title>Login</title>
</head>
<body>      
    <div class = "center">

        <h1>Signup</h1>

        <form method="post" >
            {% for field in form %}
                    <div class="txt_field">
                        {{ field}}
                        <span></span>
                        <label for="{{ field.id_for_label }}">{{field.label}} :</label>
                    
                    </div>
            {% endfor %}

           



            
            
          
           <input type="submit" value="Signup">
            {%  csrf_token %}
            <div class="signup_link">
                    Déjà Membre ! <a href="{% url 'login' %}">login</a>

            </div> 
        </form>


    </div>
    
    
    
</body>
</html>

forum/templates/forum/accueil.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>
<body>

 
        <h1>E-Forum</h1>
        
        <ul>
            {% for blog in blogs %}
              <li>
                <p>{{ blog.author}} :{{ blog.title }} creé le {{ blog.date_created|date:"d-m-Y"}}

                  <ul>
                    
                    {% for msg in blog.message_set.all %}
                                <li>
                                   {{ msg.content}}
                                </li>
                    {% endfor %}

                    {% for blog1 in blog.blog_set.all %}
                              <li>
                                {{ blog1.author}} :{{ blog1.title }} creé le {{ blog1.date_created|date:"d-m-Y"}}
                                
                                    <ul>
                                      {% for msg in blog.message_set.all %}
                                             <li>
                                              {{ msg.content}}
                                            </li>
                                      {% endfor %}

                                    </ul>
                                    
                                     
                              </li>
                              <form action="" method="post" >
                                {% csrf_token %}
                                {{ form1.as_p}}
                                <input type="hidden" name="blog" value = "{{ blog.id}}">
                                               
                                <input type="submit" value="Envoyer">
                              </form>
                    {% endfor %}
                    
                
                      
                
                  </ul>
                </p>
                
                
              </li>
              

            {% endfor %}
            
          </ul>
          <br><br><br>
       
  <p>
      Créer une blog
      <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Envoyer">
      </form>

  </p>
  </form>
</body>
</html>